# Grafana Datasources Configuration for Development
apiVersion: 1

datasources:
  # Loki for log aggregation
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: true
    editable: true
    jsonData:
      maxLines: 5000
      timeout: 60
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "executionId=([\\w-]+)"
          name: Execution ID
          url: "$${__value.raw}"
        - datasourceUid: loki
          matcherRegex: "workflowId=([\\w-]+)"
          name: Workflow ID
          url: "$${__value.raw}"
        - datasourceUid: loki
          matcherRegex: "userId=([\\w-]+)"
          name: User ID
          url: "$${__value.raw}"

  # TestData for development (if needed)
  - name: TestData
    type: testdata
    uid: testdata
    access: proxy
    isDefault: false