# Clixen AI - Loki Development Configuration
# Optimized for $9 SlipLane server with maximum logging detail
# 30-day retention policy

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: debug

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Query configuration for development
query_scheduler:
  max_outstanding_requests_per_tenant: 512

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true

# Schema optimized for development workload
schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

# Development-friendly limits (maximum detail)
limits_config:
  # Logging limits - maximum verbosity
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 720h  # 30 days
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  
  # Rate limits - generous for development
  per_stream_rate_limit: 1GB
  per_stream_rate_limit_burst: 2GB
  ingestion_rate_mb: 256
  ingestion_burst_size_mb: 512
  
  # Query limits
  max_concurrent_tail_requests: 50
  max_query_parallelism: 16
  max_query_length: 12000h  # Allow very long queries
  max_query_series: 100000
  max_streams_matchers_per_query: 1000
  
  # Size limits
  max_line_size: 256KB
  max_entries_limit_per_query: 100000
  
  # Retention - 30 days
  retention_period: 720h
  
  # Allow complex queries for debugging
  max_chunks_per_query: 20000000
  max_query_lookback: 720h

# Storage configuration for development
storage_config:
  filesystem:
    directory: /loki/chunks

# Compactor for log retention
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 50

# Table manager for cleanup
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days

# Ruler for alerting (disabled in dev)
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: false

# Analytics disabled for performance
analytics:
  reporting_enabled: false

# Ingester configuration
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s